changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🧪 Maintenance"
      labels:
        - chore
        - documentation
    - title: "⚡ Performance Improvements"
      labels:
        - performance
