http_port 3128
access_log /var/log/squid/access.log

# allow from localhost
http_access allow localhost

# Whitelist
acl allowed_domains dstdomain \
    .anthropic.com \
    .github.com \
    .githubusercontent.com \
    .pypi.org \
    .pythonhosted.org \
    .npmjs.com \
    .huggingface.co \
    docs.rs \
    .qiita.com \
    .zenn.dev \
    code.claude.com

# Allow port http / https connect
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Deny unsafe port
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Allow whitelist domain
http_access allow allowed_domains
http_access allow CONNECT allowed_domains

# Block others
http_access deny all

# Disable cache
cache deny all

# Exclude proxy information
forwarded_for off
via off
